queue_rules:
  - name: default
    speculative_checks: 20
    batch_size: 20
    conditions:
      - "#check-pending=0"
      - "#check-success>=2"
      - base=main

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - "#check-pending=0"
      - "#check-success>=2"
      - base=main
      - or:
        - author~=^dependabot(|-preview)\[bot\]$
        - author=PurpleBooth
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
