queue_rules:
  - name: default
    speculative_checks: 20
    batch_size: 20
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
