options:
  prev_tag: versio-prev

projects:
- name: common-pipelines
  id: 1
  tag_prefix: ''
  labels: releases
  version:
    tags:
      default: 0.1.0

sizes:
  use_angular: true
  none: [ci, '-']
