on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.3
      with:
        fetch-depth: 0
    - name: Install cocogitto
      uses: PurpleBooth/common-pipelines/.github/actions/install-cocogitto@main
    - name: Check projects
      run: cog check
