on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
    - name: Install versio
      run: |
        sudo apt-get update
        sudo apt-get install -y libgpgme11-dev
        cargo install versio
    - name: Check projects
      run: versio check
    - name: Print changes
      run: versio plan
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_USER: ${{ github.actor }}
