on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
  merge_group:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Conventional commit check
      uses: cocogitto/cocogitto-action@v3
      with:
        check-latest-tag-only: true
