on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Conventional commit check
      uses: cocogitto/cocogitto-action@v3
      with:
        check-latest-tag-only: true