on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2
      with:
        fetch-depth: 0
    - name: Install versio
      run: |
        sudo apt-get update
        sudo apt-get install -y libgpgme11-dev
        cargo install versio
    - name: Check projects
      run: versio check
