on:
  workflow_call:
    inputs:
      current_version:
        description: 'THe current version'
        type: string
        required: true
    secrets:
      cargo_token:
        description: 'CARGO_TOKEN to use'
        type: string
        required: true


jobs:
  release-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout the repository
        with:
          ref: v${{ inputs.current_version }}
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: default
      - env:
          CARGO_TOKEN: ${{ secrets.cargo_token }}
        run: |
          cargo login "$CARGO_TOKEN"
          cargo publish
