name: Docker Image CI

on:
  push:
    branches: [ '*' ]
  pull_request:
  pull_request_target:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref || github.ref }}
      - run: echo $VAR_A
        env:
          VAR_A: ${{ github.head_ref || github.ref }}
