on:
  workflow_call:
    inputs:
      current_version:
        description: The current version
        type: string
        required: true
      platforms:
        type: string
        description: List of target platforms for build
        required: false
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        lfs: true
        ref: v${{ inputs.current_version }}
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - run: echo ::set-output "name=repository::$( echo "ghcr.io/$REPOSITORY" | tr
        '[:upper:]' '[:lower:]')"
      id: docker
      name: Turn repository name into docker registry name
      env:
        REPOSITORY: ${{ github.repository }}
    - name: Test build
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        pull: true
        platforms: ${{ inputs.platforms }}
        cache-to: type=registry,ref=${{ steps.docker.outputs.repository }}:cache,mode=max
        cache-from: |
          type=registry,ref=${{ steps.docker.outputs.repository }}:git-${{ github.sha }}
          type=registry,ref=${{ steps.docker.outputs.repository }}:v${{ inputs.current_version }}
          type=registry,ref=${{ steps.docker.outputs.repository }}:latest
          type=registry,ref=${{ steps.docker.outputs.repository }}:cache
        tags: |-
          ${{ steps.docker.outputs.repository }}:git-${{ github.sha }}
          ${{ steps.docker.outputs.repository }}:latest
          ${{ steps.docker.outputs.repository }}:v${{ inputs.current_version }}
