on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      platforms:
        type: string
        description: List of target platforms for build
        required: false
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
    - run: echo "repository=$( echo "ghcr.io/$REPOSITORY" | tr '[:upper:]' '[:lower:]')"  >> "$GITHUB_OUTPUT"
      id: docker
      env:
        REPOSITORY: ${{ github.repository }}
    - name: Test build
      uses: docker/build-push-action@v6.6.1
      with:
        context: .
        push: false
        pull: true
        platforms: ${{ inputs.platforms }}
        cache-from: |
          type=registry,ref=$${{ steps.docker.outputs.repository }}:git-${{ github.sha }}
          type=registry,ref=${{ steps.docker.outputs.repository }}:latest
          type=registry,ref=${{ steps.docker.outputs.repository }}:cache
        tags: |-
          ${{ steps.docker.outputs.repository }}:git-${{ github.sha }}
          ${{ steps.docker.outputs.repository }}:latest
