on:
  push:
    branches:
      - '*'
  pull_request:
  merge_group:
  workflow_dispatch:
  workflow_call:
    inputs:
      platforms:
        type: string
        description: List of target platforms for build
        required: false
        default: linux/amd64,linux/arm64
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - run: echo "repository=$( echo "ghcr.io/$REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        id: docker
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ steps.docker.outputs.repository }}
          tags: |
            type=raw,value=latest
            type=sha
      - name: Test build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          push: false
          pull: true
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=oci,dest=/tmp/docker-image-cache.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-cache
          path: /tmp/docker-image-cache.tar
