on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - run: echo ::set-output "name=repository::$( echo "ghcr.io/$REPOSITORY" | tr
        '[:upper:]' '[:lower:]')"
      id: docker
      env:
        REPOSITORY: ${{ github.repository }}
    - name: Test build
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: false
        pull: true
        cache-to: type=registry,ref=${{ steps.docker.outputs.repository }}:cache,mode=max
        cache-from: |
          type=registry,ref=${{ steps.docker.outputs.repository }}:latest
          type=registry,ref=${{ steps.docker.outputs.repository }}:cache
        tags: |-
          ${{ steps.docker.outputs.repository }}:git-${{ github.sha }}
          ${{ steps.docker.outputs.repository }}:latest
