on:
  workflow_call:
    inputs:
      current_version:
        description: The current version
        type: string
        required: true
      platforms:
        type: string
        description: List of target platforms for build
        required: false
        default: linux/amd64,linux/arm64
jobs:
  docker-push:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          lfs: true
          ref: v${{ inputs.current_version }}
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: echo "repository=$( echo "ghcr.io/$REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        id: docker
        name: Turn repository name into docker registry name
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ steps.docker.outputs.repository }}
          tags: |
            type=edge,branch=main
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest
            type=semver,pattern={{version}},value=v${{ inputs.current_version }},prefix=v
            type=semver,pattern={{version}},value=v${{ inputs.current_version }}
            type=sha
      - name: Deploy build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        id: build-and-push
        with:
          context: .
          push: true
          pull: true
          sbom: true
          provenance: mode=max
          platforms: ${{ inputs.platforms }}
          github-token: ${{ github.token }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=registry,oci-mediatypes=true,compression=estargz,force-compression=true
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ steps.docker.outputs.repository }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
