on:
  workflow_call:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PurpleBooth/gfmfmt-action@v1.0.5
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13

