on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_formatting:
        required: false
        default: false
        type: boolean

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: PurpleBooth/gfmfmt-action@v2.0.1
        if: inputs.skip_formatting == false
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13

