on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_formatting:
        required: false
        default: false
        type: boolean

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      name: Checkout
    - uses: PurpleBooth/gfmfmt-action@v2.0.13
      name: Check markdown formatting
      if: inputs.skip_formatting == false
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
      name: Check links are valid

