on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: markdown-check-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: PurpleBooth/gfmfmt-action@v2.0.0
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13

