on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_formatting:
        required: false
        default: false
        type: boolean

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      name: Checkout
    - uses: PurpleBooth/gfmfmt-action@v2.0.14
      name: Check markdown formatting
      if: inputs.skip_formatting == false
      with:
        pattern: '^(?!\.\/(?:CHANGELOG\.md|\.github\/.*)).*\.md$'
    - name: Check links are valid
      uses: umbrelladocs/action-linkspector@v1
      with:
        reporter: github-check
        github_token: ${{ secrets.github_token }}
