on:
  workflow_call:
    inputs:
      current_version:
        description: The current version
        type: string
        required: true
      previous_version:
        description: The previous version
        type: string
        required: true
    secrets:
      cargo_token:
        description: CARGO_TOKEN to use
        required: true


jobs:
  release-crate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      name: Checkout the repository
      with:
        ref: v${{ inputs.current_version }}
        fetch-depth: 0
    - uses: dtolnay/rust-toolchain@master
      name: Install rust stable
      with:
        toolchain: stable
    - env:
        CARGO_TOKEN: ${{ secrets.cargo_token }}
      name: Publish to cargo
      run: |
        cargo login "$CARGO_TOKEN"
        cargo publish

  github-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      name: Checkout the repository
      with:
        ref: v${{ inputs.current_version }}
        fetch-depth: 0
    - uses: cargo-bins/cargo-binstall@main
      name: Install cargo binstall
    - shell: bash
      run: cargo binstall --no-confirm --locked cocogitto
    - run: cog changelog --at "$TAG_V" > CHANGELOG.md
      shell: bash
      env:
        TAG_V: v${{ inputs.current_version }}
    - env:
        GITHUB_TOKEN: ${{ github.token }}
      id: create_release
      name: Create gitub release
      uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
      with:
        allowUpdates: true
        token: ${{ github.token }}
        bodyFile: CHANGELOG.md
        name: Release v${{ inputs.current_version }}
        tag: v${{ inputs.current_version }}
