on:
  workflow_call:
    inputs:
      current_version:
        description: 'The current version'
        type: string
        required: true
      previous_version:
        description: 'The previous version'
        type: string
        required: true
    secrets:
      cargo_token:
        description: 'CARGO_TOKEN to use'
        required: true


jobs:
  release-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
        name: Checkout the repository
        with:
          ref: v${{ inputs.current_version }}
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: default
      - env:
          CARGO_TOKEN: ${{ secrets.cargo_token }}
        run: |
          cargo login "$CARGO_TOKEN"
          cargo publish

  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
        name: Checkout the repository
        with:
          ref: v${{ inputs.current_version }}
          fetch-depth: 0
      - uses: PurpleBooth/changelog-action@v0.1.1
        with:
          args: -v v${{ inputs.previous_version }}..v${{ inputs.current_version }}
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        id: create_release
        uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          token: ${{ github.token }}
          bodyFile: CHANGELOG.md
          name: Release v${{ inputs.current_version }}
          tag: v${{ inputs.current_version }}
