on:
  push:
    branches:
    - main

jobs:
  lint-pipeline:
    uses: armakuni/github-actions/.github/workflows/lint-pipeline.yml@a5fb943d5c31fcfaa03d562362224551d3e25acb # v0.19.4


  release:
    if: github.ref == 'refs/heads/main'
    needs:
     - lint-pipeline
    outputs:
      version_bump: ${{ steps.current_version.outputs.current_version != steps.previous_version.outputs.previous_version }}
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@cargo-binstall
        name: Install cargo binstall
      - name: Get tags
        run: git fetch --tags origin
      - shell: bash
        run: cargo binstall --no-confirm cargo-edit
      - shell: bash
        run: cargo binstall --no-confirm --locked cocogitto
      - id: previous_version
        run: |
          cog get-version | tee .version
          echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash
      - name: Semver release
        id: release
        run: |
          git config --global user.name "cog-bot"
          git config --global user.email "cog@example.com"
          cog bump --auto
      - id: current_version
        run: |
          cog get-version | tee .version
          echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash

  github-release:
    if: needs.release.outputs.version_bump
    runs-on: ubuntu-latest
    needs:
    - release
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      name: Checkout the repository
      with:
        ref: v${{  needs.release.outputs.current_version }}
        fetch-depth: 0
    - uses: PurpleBooth/changelog-action@619c4b782e4d2791e527361acdad0539b4e500d3 # v0.3.4
      name: Generate the changelog
      with:
        args: -v v${{ needs.release.outputs.previous_version }}..v${{ needs.release.outputs.current_version }}
    - env:
        GITHUB_TOKEN: ${{ github.token }}
      name: Generate the github release
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        token: ${{ github.token }}
        bodyFile: CHANGELOG.md
        name: Release v${{  needs.release.outputs.current_version  }}
        tag: v${{  needs.release.outputs.current_version  }}
