on:
  push:
    branches:
    - main

jobs:


  release:
    if: github.ref == 'refs/heads/main'
    outputs:
      version_bump: ${{ steps.current_version.outputs.current_version != steps.previous_version.outputs.previous_version }}
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Get tags
        run: git fetch --tags origin
      - shell: bash
        run: cargo install cargo-edit
      - shell: bash
        run: cargo install --locked cocogitto
      - id: previous_version
        run: |
          cog get-version | tee .version
          echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash
      - name: Semver release
        id: release
        run: |
          git config --global user.name "cog-bot"
          git config --global user.email "cog@example.com"
          cog bump --auto
      - id: current_version
        run: |
          cog get-version | tee .version
          echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash

  github-release:
    if: needs.release.outputs.version_bump
    runs-on: ubuntu-latest
    needs:
    - release
    steps:
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
      with:
        ref: v${{  needs.release.outputs.current_version }}
        fetch-depth: 0
    - uses: PurpleBooth/changelog-action@v0.3.3
      name: Generate the changelog
      with:
        args: -v v${{ needs.release.outputs.previous_version }}..v${{ needs.release.outputs.current_version
          }}
    - env:
        GITHUB_TOKEN: ${{ github.token }}
      name: Generate the github release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        token: ${{ github.token }}
        bodyFile: CHANGELOG.md
        name: Release v${{  needs.release.outputs.current_version  }}
        tag: v${{  needs.release.outputs.current_version  }}
