env:
  RUST_BACKTRACE: 1

on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      run_on_windows:
        description: Enable checks on windows
        default: true
        required: false
        type: boolean
      run_minimal_version_check:
        description: Test against minimal versions
        default: false
        required: false
        type: boolean
      windows_before_script:
        default: ''
        required: false
        type: string
      ubuntu_before_script:
        default: ''
        required: false
        type: string
      mac_before_script:
        default: ''
        required: false
        type: string


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
    - uses: actions/cache@v4
      name: Setup the cache
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1.0.7
      name: Setup the stable rust toolchain
      with:
        profile: minimal
        toolchain: stable
        default: true
    - run: cargo check
      name: Check package and all of its dependencies for errors

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          pre_script: ${{ inputs.mac_before_script }}
        - os: ubuntu-latest
          pre_script: ${{ inputs.ubuntu_before_script }}
        - os: windows-latest
          pre_script: ${{ inputs.windows_before_script }}
    steps:
    - run: ${{ matrix.pre_script }}
      name: Install dependencies
      if: (runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )) && matrix.pre_script != ''
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
    - uses: actions/cache@v4
      name: Setup the cache
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1.0.7
      name: Setup the stable rust toolchain
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        profile: minimal
        toolchain: stable
        default: true
    - run: cargo test
      name: Execute all unit and integration tests and build examples
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )

  builds-with-minimal-deps:
    if: inputs.run_minimal_version_check == true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          pre_script: ${{ inputs.mac_before_script }}
        - os: ubuntu-latest
          pre_script: ${{ inputs.ubuntu_before_script }}
        - os: windows-latest
          pre_script: ${{ inputs.windows_before_script }}
    steps:
    - run: ${{ matrix.pre_script }}
      name: Install dependencies
      if: (runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )) && matrix.pre_script != ''
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
    - uses: actions/cache@v4
      name: Setup the cache
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1.0.7
      name: Setup the nightly rust toolchain
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        profile: minimal
        toolchain: nightly
        default: true
    - run: rm Cargo.lock || true
      shell: bash
      name: Remove any existing dependency calculations
    - run: cargo build -Z minimal-versions
      name: Build with minimum versions of dependencies
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )

  lints:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
        - os: ubuntu-latest
        - os: windows-latest
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      if: runner.os != 'Windows'
      uses: Homebrew/actions/setup-homebrew@master
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
    - uses: actions/cache@v4
      name: Setup the cache
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1.0.7
      name: Setup the nightly rust toolchain
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        profile: minimal
        toolchain: nightly
        default: true
        components: rustfmt, clippy
    - run: cargo fmt --all -- --check
      name: Check the formatting of the code
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
    - run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::all -D clippy::pedantic
      name: Lint the code with clippy
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
        
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
    - uses: actions/cache@v4
      name: Setup the cache
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: rustsec/audit-check@v1.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      name: Audit check cargo packages
      
  security-audit-minimal:
    if: inputs.run_minimal_version_check == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
    - uses: actions/cache@v4
      name: Setup the cache
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1.0.7
      name: Setup the nightly rust toolchain
      with:
        profile: minimal
        toolchain: nightly
        default: true
    - uses: actions-rs/cargo@v1.0.3
      name: Install the oldest possible versions of dependencies
      with:
        command: update
        args: -Z minimal-versions
    - uses: rustsec/audit-check@v1.4.1
      name: Audit check cargo packages
      with:
        token: ${{ github.token }}
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          pre_script: ${{ inputs.mac_before_script }}
        - os: ubuntu-latest
          pre_script: ${{ inputs.ubuntu_before_script }}
        - os: windows-latest
          pre_script: ${{ inputs.windows_before_script }}
    steps:
    - run: ${{ matrix.pre_script }}
      name: Install dependencies
      if: (runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )) && matrix.pre_script != ''
    - uses: actions/checkout@v4.1.3
      name: Checkout the repository
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
    - uses: actions/cache@v4
      name: Setup the cache
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        path: |
          .cache
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1.0.7
      name: Setup the stable rust toolchain
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
      with:
        profile: minimal
        toolchain: stable
        default: true
    - run: cargo bench
      name: Execute all benchmarks
      if: runner.os != 'Windows' || ( runner.os == 'Windows' && inputs.run_on_windows == true )
