on:
  workflow_call:
    inputs:
      run_on_windows:
        description: 'Enable checks on windows'
        default: true
        required: false
        type: boolean
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: |
            .cache
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: check
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
      - uses: actions/cache@v2.1.6
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          path: |
            .cache
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.7
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1.0.3
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          command: test
  lints:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
      - uses: actions/cache@v2.1.6
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          path: |
            .cache
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.7
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          profile: minimal
          toolchain: nightly
          default: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1.0.3
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1.0.3
        if: runner.os != 'Windows' || ( runner.os != 'Windows' && inputs.run_on_windows == true )
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings -Dclippy::all -D clippy::pedantic -D clippy::cargo
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout the repository
      - uses: actions/cache@v2.1.6
        name: Cache cargo
        with:
          path: |
            .cache
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/audit-check@v1.2.0
        name: Audit check cargo packages
        with:
          token: ${{ github.token }}