on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
  merge_group:

jobs:
  check-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install Shfmt
        uses: taiki-e/install-action@5ffe29a8b19894ab68b6dc6f8d07142b719c3735 # v2
        with:
          tool: shfmt
      - name: Install ShellCheck
        uses: taiki-e/install-action@5ffe29a8b19894ab68b6dc6f8d07142b719c3735 # v2
        with:
          tool: shellcheck
      - name: Run Shfmt
        run: shfmt --find . | xargs shfmt --simplify --diff
      - name: Run ShellCheck
        run: shfmt --find . | xargs shellcheck
