on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
  merge_group:

jobs:
  check-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Shfmt
        uses: taiki-e/install-action@c87777c3160ce0cfd8fc286df47224d2449cb76b # v2
        with:
          tool: shfmt
      - name: Install ShellCheck
        uses: taiki-e/install-action@c87777c3160ce0cfd8fc286df47224d2449cb76b # v2
        with:
          tool: shellcheck
      - name: Run Shfmt
        run: shfmt --find . | xargs shfmt --simplify --diff
      - name: Run ShellCheck
        run: shfmt --find . | xargs shellcheck
