on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:
  workflow_call:
  merge_group:

jobs:
  check-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install Shfmt
        uses: taiki-e/install-action@9bef7e9c3d7c7aa986ef19933b0722880ae377e0 # v2
        with:
          tool: shfmt
      - name: Install ShellCheck
        uses: taiki-e/install-action@9bef7e9c3d7c7aa986ef19933b0722880ae377e0 # v2
        with:
          tool: shellcheck
      - name: Run Shfmt
        run: shfmt --find . | xargs shfmt --simplify --diff
      - name: Run ShellCheck
        run: shfmt --find . | xargs shellcheck
